services:
  backend:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bank_cards
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    container_name: bank_cards_postgres
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:8.2.0
    container_name: bank_cards_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}


volumes:
  bank_postgres_data:
